server:
  port: 8082

spring:
  application:
    name : sales-items
  datasource:
    url: jdbc:postgresql://sales-items-db:5432/items_db
    username: admin
    password: password
    driver-class-name : org.postgresql.Driver

  config:
    import : configserver:http://sales-config-server:8888/

  jpa:
    hibernate :
      ddl-auto : update
    show-sql : true
    properties:
      hibernate:
        dialect : org.hibernate.dialect.PostgreSQLDialect

