server:
  port: 8083

spring:
  application:
    name : sales-orders
  datasource:
    url: jdbc:postgresql://sales-orders-db:5432/orders_db
    username: admin
    password: password
    driver-class-name : org.postgresql.Driver
  jpa:
    hibernate :
      ddl-auto : update
    show-sql : true
    properties:
      hibernate:
        dialect : org.hibernate.dialect.PostgreSQLDialect
